name: maestro
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.0
  - numpy>=1.24
  - scipy>=1.9
  - scikit-learn>=1.2
  - matplotlib>=3.7
  - pandas>=1.5
  - hydra-core>=1.3
  - gymnasium>=0.28
  - pip
  - pip:
      - ptflops>=0.7
      - tqdm>=4.65
      - pyyaml>=6.0
