defaults: [../defaults]
run:
  id: lofo_classification
  total_episodes: 5
  dry_run: true
tasks:
  - configs/tasks/classification.yaml
eval_tasks:
  - configs/tasks/detection.yaml
teacher:
  hidden_dim: 64
  dataset_head_dim: 64
  policy_hidden: [128, 128]
  value_hidden: [128, 128]
