name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest gymnasium torch matplotlib
      - name: Lint
        run: |
          python -m compileall maestro
      - name: Run tests
        run: |
          pytest -q
      - name: Debug rollout
        run: |
          python scripts/evaluate.py --episodes 1 --steps 5 --out runs/debug.jsonl
