name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest gymnasium torch matplotlib
      - name: Lint
        run: |
          python -m compileall maestro
      - name: Run tests
        run: |
          pytest -q
      - name: Debug rollout
        run: |
          python scripts/run_meta_train.py --config configs/meta_train/small_cpu_debug.yaml --dry-run
          python scripts/run_eval.py --config configs/meta_train/lofo_classification.yaml
